# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee26dbf54d11af82f5b7966d703c43d8441e0e9af915bcaa85d06cfb3c26df6b9c885e723c6e7966e38013416455eeb44309817ef9ba32ca86d93babc58a4d6b

test:
  secret_key_base: 3786577c1186bbb0974d072e47c49aef1002464e6ed72d1942c304b78a7ab334e5a44e65f513f1e2436a3ddb6f6e84513198971329668d9c47580428726cb29d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
